### ISSUE TITLE
Registration Screen

### ISSUE THREAD

**Issue by nat212** [cos301-2019-se/Amazon-Dash#22]
Need to create a frontend registration screen that uses the registration endpoint.

**Comment by brendan-bath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Registration](https://trello.com/c/5gny0k0N/26-registration)

**Comment by brendan-bath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Registration](https://trello.com/c/5gny0k0N/26-registration)

**Comment by brendan-bath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Registration](https://trello.com/c/5gny0k0N/26-registration)
