### ISSUE TITLE
Stop/Restart/Start Functionality on instances

### ISSUE THREAD

**Issue by nat212** [cos301-2019-se/Amazon-Dash#23]
Instances need to be able to be stopped, restarted, and started.

**Comment by brendan-bath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Stop/Restart/Start Functionality on instances](https://trello.com/c/NC5gMYQW/24-stop-restart-start-functionality-on-instances)

**Comment by brendan-bath** [comment]
- [ ] Frontend
- [x] Backend
