### ISSUE TITLE
Make module to handle backend calls in frontend

### ISSUE THREAD

**Issue by nat212** [cos301-2019-se/Amazon-Dash#25]
There needs to be a module in the frontend (possible a `vuex` module) that handles API calls. The URL needs to be not hardcoded, and preferably retrieved from an environment variable.

**Comment by brendan-bath** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make module to handle backend calls in frontend](https://trello.com/c/ZD2D0Ei2/22-make-module-to-handle-backend-calls-in-frontend)

**Comment by 1tsS0meth1ng** [comment]
-[ ] Frontend

**Comment by brendan-bath** [comment]
- [ ] Frontend
